### ISSUE TITLE
カメラの固定化

### ISSUE THREAD

**Issue by Tsutomu-H** [konan-pbl-2017/teamA#6]
TemplateRPG2D.javaにて、カメラを実行時の初期位置で固定させたまま、プレイヤーのみ移動するようにしたいのですが、実装方法がわかりません。どうすればよいのか教えてください。

現状：カメラがプレイヤーの移動に合わせて視点も移動する状態(プレイヤーの位置によってはエリアが見切れる状態)
実装したい状態：プレイヤーの挙動に関係なく、初期位置のまま固定化した状態(エリア全体が常に見渡せる状態)

**Comment by n-nitta** [comment]
setMapCenter(x, y) でマップの中心、setViewRange(w, h) でマップの表示範囲を指定できます。
map.getMapWeight() と map.getMapHeight() でマップの大きさを取ってくることができます。
